component:
  dashboard:
    image: badal773/dashboard:954f5e6a-11-20
    artifact_id: 21
  orchestrator:
    image: badal773/orchestrator:9099b2ff-8-78
    artifact_id: 66
  lens:
    image: badal773/lens:954f5e6a-12-24
    artifact_id: 24
  image-scanner:
    image: badal773/image-scanner:9099b2ff-15-80
    artifact_id: 69
  kubewatch:
    image: badal773/kubewatch:9099b2ff-13-77
    artifact_id: 67
  kubelink:
    image: badal773/kubelink:954f5e6a-14-22
    artifact_id: 23
  notifyer-deploy:
    image: badal773/notifyer-deploy:9099b2ff-16-81
    artifact_id: 70
  casbin:
    image: badal773/casbin:954f5e6a-17-29
    artifact_id: 29
  app-sync-cronjob:
    image: badal773/app-sync-cronjob:9099b2ff-18-84
    artifact_id: 73
  git-sensor:
    image: badal773/git-sensor:9099b2ff-19-83
    artifact_id: 72
